# Generated by Django 5.1.4 on 2024-12-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono para contacto (opcional)', max_length=20, verbose_name='Teléfono'),
        ),
    ]
