# Generated by Django 5.1.4 on 2024-12-29 20:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='mascota',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible para adopción'), ('adoptado', 'Adoptado'), ('en_tratamiento', 'En tratamiento')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mascota',
            name='unidad_edad',
            field=models.CharField(choices=[('meses', 'Meses'), ('años', 'Años')], default='meses', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='biografia',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
