# Generated by Django 5.1.4 on 2024-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_alter_mascota_options_mascota_creado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biografia',
        ),
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
