# Generated by Django 5.1.4 on 2024-12-29 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_remove_profile_biografia_alter_profile_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mascotas/')),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='adopcion.mascota')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
