# Generated by Django 5.1.4 on 2024-12-30 02:05

import adopcion.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la mascota', max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], default='perro', help_text='Tipo de mascota', max_length=10, verbose_name='Tipo')),
                ('raza', models.CharField(blank=True, help_text='Raza de la mascota (opcional)', max_length=100, verbose_name='Raza')),
                ('edad', models.PositiveIntegerField(default=1, help_text='Edad en años', verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', help_text='Sexo de la mascota', max_length=1, verbose_name='Sexo')),
                ('tamanio', models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], default='M', help_text='Tamaño de la mascota', max_length=1, verbose_name='Tamaño')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la mascota', verbose_name='Descripción')),
                ('foto', models.ImageField(blank=True, help_text='Foto de la mascota', null=True, upload_to=adopcion.models.mascota_imagen_path, verbose_name='Foto')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('adoptada', models.BooleanField(default=False, help_text='Indica si la mascota ya fue adoptada', verbose_name='Adoptada')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que publica la mascota', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='¿Por qué quieres adoptar esta mascota?', verbose_name='Motivo')),
                ('experiencia_previa', models.TextField(help_text='¿Has tenido mascotas antes? Cuéntanos tu experiencia.', verbose_name='Experiencia previa')),
                ('vivienda', models.CharField(help_text='¿En qué tipo de vivienda vives? (casa, departamento, etc.)', max_length=50, verbose_name='Tipo de vivienda')),
                ('tiene_patio', models.BooleanField(default=False, help_text='¿Tu vivienda cuenta con patio?', verbose_name='¿Tiene patio?')),
                ('otros_animales', models.TextField(blank=True, help_text='¿Tienes otras mascotas? Cuéntanos sobre ellas.', verbose_name='Otros animales')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada')], default='P', max_length=1, verbose_name='Estado')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='adopcion.mascota', verbose_name='Mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_adopcion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de adopción',
                'verbose_name_plural': 'Solicitudes de adopción',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
